### ISSUE TITLE
Tema central del proyecto

### ISSUE THREAD

**Issue by alu0100699968** [alu0100699968/PL_LDE#1]
Necesitamos decidir un tema. @alu0100502923 @alu0100614220 @alu0100696455

**Comment by alu0100614220** [comment]
Podriamos crear un DSL que nos permita crear de forma fácil criticas para películas, y si la crítica es buena o mala

**Comment by alu0100699968** [comment]
Me gusta tu idea @alu0100614220 #SigueAsíCampeón

**Comment by alu0100696455** [comment]
Tema: Creación de críticas de películas

**Comment by alu0100699968** [comment]
Perfecto :+1:
